### ISSUE TITLE
Sub-menus do not respect single click

### ISSUE THREAD

**Issue by LordGrimmauld** [imgurbot12/rmenu#12]
The Submenu of e.g. powermenu does not respect the single click property being set. So even if the first powermenu window is single click, the confirmation menu will require double click no matter what. This feels inconsistent.. Sorry i haven't noticed earlier while testing the mouse ui improvements, i understand this is quite an edge case here.

**Comment by imgurbot12** [comment]
No worries, nice catch.

I unfortunately can't get to it right away since I'm traveling at the moment, but I'll be back and on it in a day or so.

Thanks!

**Comment by imgurbot12** [comment]
@LordGrimmauld It looks like rmenu didn't have a way to keep the plugin configuration in context for all multi-stage implementations. I've used a runtime env-variable to help preserve the configurations between stages.

A [branch](https://github.com/imgurbot12/rmenu/tree/fix/multi-stage) is available for testing. It seems to work well so far :)
Lmk what you think.

**Comment by imgurbot12** [comment]
fix merged and pushed to master. new tag made: [v1.2.2](https://github.com/imgurbot12/rmenu/releases/tag/v1.2.2)

**Comment by LordGrimmauld** [comment]
Aight, will prep the packaging then
